# Generated by Django 6.0.6 on 2026-07-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('TASK', 'Task'), ('DEPARTMENT', 'Department'), ('USER', 'User'), ('REPORT', 'Report'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
    ]
